version: "3.8"

services:
  app:
    build:
      context: app/
      dockerfile: ./Dockerfile
    command: bash
    tty: true

#      args:
#        DEBIAN_FRONTEND: noninteractive
#        BASE_DIR: /usr/src/app/


