version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    command: bash
    tty: true
    volumes:
      - :/usr/src/app

#      args:
#        DEBIAN_FRONTEND: noninteractive
#        BASE_DIR: /usr/src/app/


