version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    command: bash
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app:rw

#      args:
#        DEBIAN_FRONTEND: noninteractive
#        BASE_DIR: /usr/src/app/


